service: misskey-crossposter

useDotenv: true

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  stage: dev
  iam:
    role:
      managedPolicies:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaRole'

functions:
  handler:
    handler: index.handler
    environment:
      NODE_ENV: ${opt:stage, self:provider.stage}
      USERMAP: ${env:USERMAP}
      MISSKEY_HOOK_SECRET: ${env:MISSKEY_HOOK_SECRET}
    url: true

package:
  patterns:
    - '!.git/**'
    - '!node_modules/**'
    - 'node_modules/misskey-js/**'
    - 'node_modules/node-fetch/**'
    - 'node_modules/twitter-api-v2/**'

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline
