service: misskey-crossposter

useDotenv: true

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  stage: dev
  iam:
    role:
      managedPolicies:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaRole'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
  vpc:
    securityGroupIds:
      - sg-f610b59c
    subnetIds:
      - subnet-0c408035072b66f05
      - subnet-0e2198b674beac6d5

functions:
  handler:
    handler: index.handler
    environment:
      NODE_ENV: ${opt:stage, self:provider.stage}
      MISSKEY_INSTANCE: ${env:MISSKEY_INSTANCE}
      MISSKEY_API_TOKEN: ${env:MISSKEY_API_TOKEN}
      MISSKEY_ADMIN: ${env:MISSKEY_ADMIN}
      REDIS_URL: ${env:REDIS_URL}
    events:
      - http:
          path: endpoint
          method: post
          cors: true

package:
  patterns:
    - 'base_profiles/**'

    - '!.git/**'
    - '!node_modules/**'
    - 'node_modules/misskey-js/**'
    - 'node_modules/twitter-api-v2/**'
    - 'node_modules/@aws-sdk/**'
    - 'node_modules/got/**'
    - 'node_modules/redis/**'

    # @aws-sdk dependencies
    - 'node_modules/@smithy/**'
    - 'node_modules/fast-xml-parser/**'
    - 'node_modules/tslib/**'
    - 'node_modules/@aws-crypto/**'
    - 'node_modules/strnum/**'

    # got dependencies
    - 'node_modules/@sindresorhus/is/**'
    - 'node_modules/@szmarczak/http-timer/**'
    - 'node_modules/cacheable-lookup/**'
    - 'node_modules/cacheable-request/**'
    - 'node_modules/decompress-response/**'
    - 'node_modules/form-data-encoder/**'
    - 'node_modules/get-stream/**'
    - 'node_modules/http2-wrapper/**'
    - 'node_modules/lowercase-keys/**'
    - 'node_modules/p-cancelable/**'
    - 'node_modules/responselike/**'
    - 'node_modules/defer-to-connect/**'
    - 'node_modules/http-cache-semantics/**'
    - 'node_modules/keyv/**'
    - 'node_modules/mimic-response/**'
    - 'node_modules/normalize-url/**'
    - 'node_modules/json-buffer/**'
    - 'node_modules/quick-lru/**'
    - 'node_modules/resolve-alpn/**'

    # redis dependencies
    - 'node_modules/@redis/**'
    - 'node_modules/cluster-key-slot/**'
    - 'node_modules/generic-pool/**'
    - 'node_modules/yallist/**'

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline
