service: misskey-crossposter

useDotenv: true

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  stage: dev
  iam:
    role:
      managedPolicies:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaRole'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'

functions:
  handler:
    handler: index.handler
    environment:
      NODE_ENV: ${opt:stage, self:provider.stage}
      MISSKEY_INSTANCE: ${env:MISSKEY_INSTANCE}
      MISSKEY_API_TOKEN: ${env:MISSKEY_API_TOKEN}
      MISSKEY_ADMIN: ${env:MISSKEY_ADMIN}
    events:
      - http:
          path: endpoint
          method: post
          cors: true

package:
  patterns:
    - 'base_profiles/**'

    - '!.git/**'
    - '!node_modules/**'
    - 'node_modules/misskey-js/**'
    - 'node_modules/node-fetch/**'
    - 'node_modules/twitter-api-v2/**'
    - 'node_modules/@aws-sdk/**'
    - 'node_modules/axios/**'

    # node-fetch dependencies
    - 'node_modules/whatwg-url/**'
    - 'node_modules/webidl-conversions/**'
    - 'node_modules/punycode/**'
    - 'node_modules/tr46/**'

    # @aws-sdk dependencies
    - 'node_modules/@smithy/**'
    - 'node_modules/fast-xml-parser/**'
    - 'node_modules/tslib/**'
    - 'node_modules/@aws-crypto/**'
    - 'node_modules/strnum/**'

    # axios dependencies
    - 'node_modules/follow-redirects/**'
    - 'node_modules/form-data/**'
    - 'node_modules/proxy-from-env/**'

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline
