on:
  push:
    branches:
      - master
  release:
    types: [released]

name: Deploy serverless function
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Get environment from event
      id: environment
      run: |
        if '${{ github.event_name == 'release' && github.event.action == 'released' }}' == 'true'; then echo ::set-output name=value::"production"; else echo ::set-output name=value::"dev"; fi

    - uses: actions/setup-node@v1
      with:
        node-version: '14'

    - run: npm ci

    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy --stage ${{ steps.environment.outputs.value }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SERVERLESS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SERVERLESS_SECRET_ACCESS_KEY }}
        TWITTER_APP_KEY: ${{ secrets.TWITTER_APP_KEY }}
        TWITTER_APP_SECRET: ${{ secrets.TWITTER_APP_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        MISSKEY_USER_ID: ${{ secrets.MISSKEY_USER_ID }}
        MISSKEY_HOOK_SECRET: ${{ secrets.MISSKEY_HOOK_SECRET }}
        MISSKEY_URL: ${{ secrets.MISSKEY_URL }}
