on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

name: Run Tests
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - uses: actions/setup-node@v1
      with:
        node-version: '14'

    - run: npm ci

    - name: Run tests
      run: npm run test
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      env:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: Hoto-Cocoa/misskey-crossposter-webhook
